### ISSUE TITLE
Support for SCCACHE

### ISSUE THREAD

**Issue by c410-f3r** [actions-rs/meta#15]
SCCACHE has [experimental Rust support](https://github.com/mozilla/sccache/blob/master/docs/Rust.md).

**Comment by svartalf** [comment]
Hey, @c410-f3r!

I think at this point it would be easier to use https://github.com/actions/cache instead.
From what I see, there are no bindings for the cache storage exist yet, so it is not clear for me, how and where we could store and load `sccache` cache between the runs.

**Comment by c410-f3r** [comment]
I see. Thank you for the information!
