### ISSUE TITLE
Tracking issue for grcov Action

### ISSUE THREAD

**Issue by svartalf** [actions-rs/meta#3]
As in https://github.com/mozilla/grcov

**Comment by svartalf** [comment]
For reference: repo is [here](https://github.com/actions-rs/grcov) and the development is going on at the `dev` branch.

**Comment by lucasbrendel** [comment]
Would this [example](https://github.com/codecov/example-rust/blob/master/README.md) by codecov be something that would be better done in a separate action? Like an actions-rs/kcov?

**Comment by svartalf** [comment]
@lucasbrendel well, maybe? I'm not sure yet, as the main focus is on the `grcov` and `tarpaulin` support right now.

I'm wondering if it would be easier just [to use](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idcontainer) the [`kcov` Docker container](https://hub.docker.com/r/kcov/kcov/) to generate report, rather then managing the same stuff in the GH Action

**Comment by lucasbrendel** [comment]
@svartalf thanks and you may be correct. I have not used tarpaulin myself but looking at the README it might already do what i need, i just need to actually try it out so then my question could become pointless.

**Comment by svartalf** [comment]
As the `grcov` Action [is published now](https://github.com/actions-rs/grcov), I'm going to close this issue; all further discussions should be in there
